/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mypluginwithjni_actions_SampleAction */

#ifndef _Included_mypluginwithjni_actions_SampleAction
#define _Included_mypluginwithjni_actions_SampleAction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mypluginwithjni_actions_SampleAction
 * Method:    getNativeMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mypluginwithjni_actions_SampleAction_getNativeMessage
  (JNIEnv *, jobject);

/*
 * Class:     mypluginwithjni_actions_SampleAction
 * Method:    getNativeint
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mypluginwithjni_actions_SampleAction_getNativeint
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
